### ISSUE TITLE
ConcurrentLinkedDequeTest.addLast() always adds the constant 1

### ISSUE THREAD

**Issue by OliverO2** [ndkoval/concurrent-linked-deque-bug#1]
https://github.com/ndkoval/concurrent-linked-deque-bug/blob/0f685f8347f5c005a60414ac1f0f0fee9316b0eb/src/ConcurrentLinkedDequeTest.kt#L15-L16

Is this intentional?

Lincheck will still raise a `LincheckAssertionError` after changing the above to:
```kotlin
    @Operation
    fun addLast(e: Int) = deque.addLast(e)
```

**Comment by ndkoval** [comment]
Thanks for the catch, fixed ✅
